/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brian' at '11/18/15 7:45 PM' with Gradle 2.6
 *
 * @author brian, @date 11/18/15 7:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
